musicip:
  container_name: "musicip"
  restart: unless-stopped
  image: justifiably/musicip
  ports:
    - 10002:10002
  volumes:
    - /int/musicip:/home/musicip
    - /srv/music/:/srv/music:ro
    - /srv/music-flac/:/srv/music-flac:ro
  